// Code generated by "stringer -type=Error"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-0]
	_ = x[StackOverflow-1]
	_ = x[StackUnderflow-2]
	_ = x[IllegalInstruction-3]
	_ = x[IllegalInstructionAccess-4]
	_ = x[DivisionByZero-5]
	_ = x[UnknownOperand-6]
}

const _Error_name = "OkStackOverflowStackUnderflowIllegalInstructionIllegalInstructionAccessDivisionByZeroUnknownOperand"

var _Error_index = [...]uint8{0, 2, 15, 29, 47, 71, 85, 99}

func (i Error) String() string {
	if i < 0 || i >= Error(len(_Error_index)-1) {
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
