// Code generated by "stringer -type=InstructionType"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Push-0]
	_ = x[Duplicate-1]
	_ = x[Plus-2]
	_ = x[Minus-3]
	_ = x[Multiply-4]
	_ = x[Divide-5]
	_ = x[Jump-6]
	_ = x[JumpIfTrue-7]
	_ = x[Equal-8]
	_ = x[End-9]
}

const _InstructionType_name = "PushDuplicatePlusMinusMultiplyDivideJumpJumpIfTrueEqualEnd"

var _InstructionType_index = [...]uint8{0, 4, 13, 17, 22, 30, 36, 40, 50, 55, 58}

func (i InstructionType) String() string {
	if i < 0 || i >= InstructionType(len(_InstructionType_index)-1) {
		return "InstructionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstructionType_name[_InstructionType_index[i]:_InstructionType_index[i+1]]
}
